/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 08:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>AJAX MySQL Table Query1</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("<style>\n");
      out.write("#searchContainer {\n");
      out.write("    position: fixed;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 70%;\n");
      out.write("    background-color: linear-gradient(180deg, rgba(228, 220, 207, 1) 0%, rgba(245, 240, 187, 1) 38%, rgba(125, 157, 156, 1) 100%);\n");
      out.write("    padding: 10px;\n");
      out.write("    z-index: 2;\n");
      out.write("    margin-top: 1%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result {\n");
      out.write("    margin-top: 50%;\n");
      out.write("    overflow-y: auto;\n");
      out.write("    max-height: calc(100vh - 200px);\n");
      out.write("    width: 70%;\n");
      out.write("    margin: 0 auto 0;\n");
      out.write("    padding: 0;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result table {\n");
      out.write("    width: 100%;\n");
      out.write("    border-collapse: collapse;\n");
      out.write("    margin-top: 4%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result th, #result td {\n");
      out.write("    border: 1px solid #dddddd;\n");
      out.write("    padding: 8px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result th {\n");
      out.write("    background-color: #f2f2f2;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result td {\n");
      out.write("    background-color: #ffffff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#result tr:nth-child(even) {\n");
      out.write("    background-color: #f2f2f2;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"searchContainer\">\n");
      out.write("        <input type=\"text\" id=\"name\" placeholder=\"성명 입력\">\n");
      out.write("         <input type=\"text\" id=\"joinDatepicker\" placeholder=\"가입날짜 선택\">\n");
      out.write("        <input type=\"text\" id=\"leaveDatepicker\" placeholder=\"탈퇴날짜 선택\">\n");
      out.write("        <button id=\"queryButton\">검색</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"result\"></div>\n");
      out.write("    <script src=\"js/queryTable.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        $(function() {\n");
      out.write("        	 $(\"#joinDatepicker\").datepicker(); // 가입날짜 캘린더 초기화\n");
      out.write("             $(\"#leaveDatepicker\").datepicker(); // 탈퇴날짜 캘린더 초기화\n");
      out.write("\n");
      out.write("            // 검색 버튼 클릭 시 결과 영역의 높이를 조절\n");
      out.write("            $('#queryButton').click(function() {\n");
      out.write("                adjustResultHeight();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            // 페이지 로드 시 테이블 결과 영역의 높이를 조절\n");
      out.write("            adjustResultHeight();\n");
      out.write("\n");
      out.write("            // 윈도우 크기가 변경될 때 테이블 결과 영역의 높이를 다시 조절\n");
      out.write("            $(window).resize(adjustResultHeight);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // 테이블 결과 영역의 높이를 조절하는 함수\n");
      out.write("        function adjustResultHeight() {\n");
      out.write("            var windowHeight = $(window).height();\n");
      out.write("            var searchContainerHeight = $('#searchContainer').outerHeight();\n");
      out.write("            var resultHeight = windowHeight - searchContainerHeight;\n");
      out.write("            $('#result').css('max-height', resultHeight + 'px');\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>    \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
