/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-26 04:20:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/board/../include/sidemenu.jsp", Long.valueOf(1707962972000L));
    _jspx_dependants.put("file:/usr/local/tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1704443287000L));
    _jspx_dependants.put("jar:file:/usr/local/tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/board/../include/header.jsp", Long.valueOf(1708416786000L));
    _jspx_dependants.put("/board/../include/footer.jsp", Long.valueOf(1708333857000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>QnA - Mak U Swag</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all2.css\">\n");
      out.write("<link rel=\"icon\" href=\"./images/CompanyLogo.png\">\n");
      out.write("<!-- 인터넷 창 아이콘에 로고 나오게 하기 -->\n");
      out.write("</head>\n");
      out.write("<body class=\"nav-expended\">\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	");
      out.write('\n');
      out.write('\n');

// session2는 로그인용
HttpSession session2 = request.getSession();
// 세션에 저장된 사용자 정보가 있는지 확인합니다.
boolean reg = (session2 != null && session.getAttribute("user") != null);

      out.write("\n");
      out.write("<header>\n");
      out.write("	<div class=\"site-header\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"site-logo\">\n");
      out.write("				<h1>\n");
      out.write("					<a href=\"main.do\"> <img src=\"./images/CompanyLogo.png\" alt=\"로고\"\n");
      out.write("						class=\"logo-img\" width=\"200px\" height=\"100px\">\n");
      out.write("					</a>\n");
      out.write("				</h1>\n");
      out.write("			</div>\n");
      out.write("			<ul\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-statelogoff user-menu\">\n");
      out.write("				");
 if(reg) { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"logout.do\"><b>Logout</b></a></li>\n");
      out.write("				");
 } else { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\"><b>Login</b></a></li>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("				");
 if(reg) { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"myPage.do\"><b>MyPage</b></a></li>\n");
      out.write("				");
 } else { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\"><b>MyPage</b></a></li>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("				");
 if(reg) { 
      out.write("\n");
      out.write("				<li class=\"menu-item menu--cart\"><a href=\"cart.do\"><b>Cart</b><span\n");
      out.write("						class=\"badge displaynone\">()</span></a></li>\n");
      out.write("				");
 } else { 
      out.write("\n");
      out.write("				<li class=\"menu-item menu--cart\"><a href=\"login.do\"><b>Cart</b><span\n");
      out.write("						class=\"badge displaynone\">()</span></a></li>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("			</ul>\n");
      out.write("			<div class=\"hamburger\" role=\"button\" aria-expanded=\"false\">\n");
      out.write("				<span class=\"patty\"> </span>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"mobile-cart\">\n");
      out.write("				<a href=\"/order/basket.html\"><span class=\"badge\"></span></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("	<div class=\"site-main\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("\n");
      out.write("			");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/177bef69e2.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<div class=\"site-nav sidebar fixed\">\n");
      out.write("	<div class=\"nav-col col-left\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"about.do\">About us</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"xans-element- xans-layout xans-layout-category site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"best100.do\">BEST 100</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"all_in_one.do\">All-in-one</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"outer.do\">Outer</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"topshort.do\">Top(short sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"toplong.do\">Top(long sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bottoms.do\">Bottoms</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bags.do\">Bags</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"accessories.do\">Accessories</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"shoes.do\">Shoes</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"women.do\">Women only</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"nav-col col-right\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-statelogoff user-menu \">\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\">Login</a></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"/member/login.html?noMemberOrder&amp;returnUrl=%2Fmyshop%2Forder%2Flist.html\">Mypage</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.youtube.com/channel/UCNzODSZC2sraPyh4lDMQhpQ?view_as=subscriber\"\n");
      out.write("					target=\"_blank\">YouTube</a>&nbsp;<i class=\"fa-brands fa-youtube\"></i></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.instagram.com/faderoom_official/\" target=\"_blank\">Instagram</a>&nbsp;<i\n");
      out.write("					class=\"fa-brands fa-instagram\"></i></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"notice.do\">Notice</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"review.do\">Review</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"qna.do\">Q&amp;A</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"faq.do\">FAQ</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"cs-info\">\n");
      out.write("			<ul>\n");
      out.write("				<li>Counseling Center <br>02 123 4567\n");
      out.write("				</li>\n");
      out.write("				<li>13:00 - 18:00 <br>sat.sun.holiday off\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<form id=\"searchBarForm\" name=\"\" action=\"search.do\"\n");
      out.write("			method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\n");
      out.write("			<input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\">\n");
      out.write("			<div\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-searchside search-bar \">\n");
      out.write("				<!--\n");
      out.write("	                    $search_page = /product/search.html\n");
      out.write("	                    $product_page = /product/detail.html\n");
      out.write("	                -->\n");
      out.write("				<fieldset>\n");
      out.write("					<legend>검색</legend>\n");
      out.write("					<input id=\"keyword\" name=\"keyword\" fw-filter=\"\" fw-label=\"검색어\"\n");
      out.write("						fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\"\n");
      out.write("						onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\" value=\"\"\n");
      out.write("						type=\"text\"><input type=\"image\"\n");
      out.write("						src=\"./images/search-icon.png\" alt=\"검색\"\n");
      out.write("						onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\">\n");
      out.write("				</fieldset>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<div class=\"main\">\n");
      out.write("\n");
      out.write("				<!-- 여기서 부터 작성 -->\n");
      out.write("				<div class=\"board\">\n");
      out.write("					<div\n");
      out.write("						class=\"xans-element- xans-board xans-board-title board-header \">\n");
      out.write("						<h3>\n");
      out.write("							<font color=\"#555555\">Q&A</font>\n");
      out.write("						</h3>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div\n");
      out.write("						class=\"xans-element- xans-board xans-board-listpackage board-list \">\n");
      out.write("						<div\n");
      out.write("							class=\"xans-element- xans-board xans-board-notice qna-list qna-notice\">\n");
      out.write("							<div class=\"list-item xans-record-\">\n");
      out.write("								<a href=\"/article/qa/5/60/\" class=\"post-link\"> <span\n");
      out.write("									class=\"number\">공지</span> <span class=\"title\">카카오 상담을\n");
      out.write("										이용해주세요!</span> <span class=\"date \">페이드룸</span>\n");
      out.write("								</a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"xans-element- xans-board xans-board-list qna-list\">\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<div\n");
      out.write("							class=\"xans-element- xans-board xans-board-empty message displaynone \">\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("						<div style=\"text-align: center;\">\n");
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</div>\n");
      out.write("						<form id=\"boardSearchForm\" name=\"\" action=\"/board/free/qna.html\"\n");
      out.write("							method=\"get\" target=\"_top\" enctype=\"multipart/form-data\">\n");
      out.write("							<input id=\"board_no\" name=\"board_no\" value=\"5\" type=\"hidden\" />\n");
      out.write("							<input id=\"page\" name=\"page\" value=\"1\" type=\"hidden\" /> <input\n");
      out.write("								id=\"board_sort\" name=\"board_sort\" value=\"\" type=\"hidden\" />\n");
      out.write("							<div\n");
      out.write("								class=\"xans-element- xans-board xans-board-search board-search-form \">\n");
      out.write("								<fieldset>\n");
      out.write("									<select id=\"search_date\" name=\"search_date\" fw-filter=\"\"\n");
      out.write("										fw-label=\"\" fw-msg=\"\">\n");
      out.write("										<option value=\"week\">일주일</option>\n");
      out.write("										<option value=\"month\">한달</option>\n");
      out.write("										<option value=\"month3\">세달</option>\n");
      out.write("										<option value=\"all\">전체</option>\n");
      out.write("									</select> <select id=\"search_key\" name=\"search_key\" fw-filter=\"\"\n");
      out.write("										fw-label=\"\" fw-msg=\"\">\n");
      out.write("										<option value=\"subject\">제목</option>\n");
      out.write("										<option value=\"content\">내용</option>\n");
      out.write("										<option value=\"writer_name\">글쓴이</option>\n");
      out.write("										<option value=\"member_id\">아이디</option>\n");
      out.write("										<option value=\"nick_name\">별명</option>\n");
      out.write("									</select> <input id=\"search\" name=\"search\" fw-filter=\"\" fw-label=\"\"\n");
      out.write("										fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" value=\"\"\n");
      out.write("										type=\"text\" /> <a href=\"#none\" class=\"search-button\"\n");
      out.write("										onclick=\"BOARD.form_submit('boardSearchForm');\"></a>\n");
      out.write("								</fieldset>\n");
      out.write("							</div>\n");
      out.write("											<div\n");
      out.write("					class=\"xans-element- xans-board xans-board-buttonlist board-admin-actions  \">\n");
      out.write("					<a href=\"./qnaWrite.do\" class=\"primary-button \"><span>WRITE</span></a>\n");
      out.write("				</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<!-- 여기까지 작성 -->\n");
      out.write("\n");
      out.write("				<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("				<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("\n");
      out.write("				");
      out.write(" \n");
      out.write("	<div class=\"site-footer\">\n");
      out.write("		<ul>\n");
      out.write("			<li>\n");
      out.write("				<span>Mak U Swag | CEO One Stone One Billion | Personal \n");
      out.write("				Info Manager Team 401 | Account No. 국민은행 12345678900 </span>\n");
      out.write("				<span>Email <a href=\"mailto:teamone401@makuswag.co.kr\" style=\"color: blue\">info@ssambbong.co.kr</a></span><br>\n");
      out.write("\n");
      out.write("			</li>\n");
      out.write("			<li><span>4 floor, Hankuk Tower, 78 Gil 8, Gangnamdae-ro, Gangnam-gu, Seoul |</span> <span>Reg.\n");
      out.write("					No. 02-123-4567 |</span> <span>Ecommerce Reg. No.\n");
      out.write("					2023-SeoulJungnang-0207</span></li>\n");
      out.write("			<li class=\"legal-links\"><a href=\"agreement.do\"\n");
      out.write("				style=\"color: blue;\">Terms of Use</a> <a\n");
      out.write("				href=\"privacy.do\" style=\"color: blue;\">Privacy Policy</a>\n");
      out.write("				<p class=\"copyright\">© 2023 Mak U Swag</p></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /board/qna.jsp(55,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/board/qna.jsp(55,7) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/qna.jsp(55,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      // /board/qna.jsp(55,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								<div class=\"list-item xans-record-\">\n");
            out.write("									<a href=\"qnaContent.do?qnaSeq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qnaSeq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"post-link\"> <span\n");
            out.write("										class=\"number\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qnaSeq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><span class=\"title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qnaTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("										<span class=\"date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("									</a>\n");
            out.write("								</div>\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /board/qna.jsp(72,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage > 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"qna.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage - 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("									style=\"display: inline-block; margin: 10px;\">&nbsp;이전</a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /board/qna.jsp(77,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/board/qna.jsp(77,7) '${pageList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/qna.jsp(77,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("page");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("									");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\n");
          out.write("									");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /board/qna.jsp(79,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page == currentPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("										<span\n");
          out.write("											style=\"display: inline-block; margin: 10px; font-weight: bold;\">&nbsp;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("										<a href=\"qna.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("											style=\"display: inline-block; margin: 10px;\">&nbsp;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /board/qna.jsp(90,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage < totalPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"qna.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("									style=\"display: inline-block; margin: 10px;\">&nbsp;다음</a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
