/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-27 10:40:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.javalec.dao.ProductKey;
import java.util.HashSet;
import java.util.Set;
import com.javalec.dto.brandDTO;
import java.util.List;

public final class brandDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.javalec.dao.ProductKey");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.javalec.dto.brandDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Product List</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Arial', sans-serif;\n");
      out.write("            background-color: #f4f4f4;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            width: 80%;\n");
      out.write("            margin: 20px;\n");
      out.write("            background-color: #fff;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th, td {\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            padding: 10px;\n");
      out.write("            text-align: left;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        img {\n");
      out.write("            max-width: 100px;\n");
      out.write("            height: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .purchase-button {\n");
      out.write("            background-color: #4caf50;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            text-align: center;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

    // 제품 정보를 받아옴
    List<brandDTO> products = (List<brandDTO>) request.getAttribute("products");

    // 중복되지 않는 제품 키를 저장할 Set
    Set<ProductKey> uniqueProductKeys = new HashSet<>();

      out.write("\n");
      out.write("<table>\n");
      out.write("    <thead>\n");
      out.write("        <tr>\n");
      out.write("            <th>Product Image</th>\n");
      out.write("            <th>Product Information</th>\n");
      out.write("        </tr>\n");
      out.write("    </thead>\n");
      out.write("    <tbody>\n");
      out.write("        <form id=\"purchaseForm\" action=\"purchase.do\" method=\"post\">\n");
      out.write("        ");

            // 받아온 제품 정보를 반복문으로 출력
            for (brandDTO product : products) {
                String productName = product.getProductName();
                List<String> availableColors = product.getAvailableColors();
                double price = product.getProductprice();
                String brand = product.getProductbrand();

                // 중복되지 않는 경우에만 출력
                ProductKey productKey = new ProductKey(brand, productName, null, price);

                if (uniqueProductKeys.add(productKey)) {
                    // DecimalFormat을 사용하여 price를 한국 수학 기호에 맞게 포맷팅
                    java.text.DecimalFormat koreanFormat = new java.text.DecimalFormat("#,###");
                    String formattedPrice = koreanFormat.format(price);
        
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/");
      out.print( product.getImagename());
      out.write("\" width=\"300\" height=\"300\"></td>\n");
      out.write("            ");

           out.print(product.getImagename());
            
            
      out.write("\n");
      out.write("            <td>\n");
      out.write("                <p>Product brand: ");
      out.print( brand );
      out.write("</p>\n");
      out.write("                <p>Product Name: ");
      out.print( productName );
      out.write("</p>\n");
      out.write("                <p>Available Colors:</p>\n");
      out.write("                <!-- 각 색상을 라디오 버튼으로 만듭니다 -->\n");
      out.write("                ");
 
                    for (String colorOption : availableColors) {
                
      out.write("\n");
      out.write("                        <input type=\"radio\" name=\"color\" value=\"");
      out.print( colorOption );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( colorOption );
      out.write("\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("                <!-- 수정 못하도록 readonly 속성 추가 -->\n");
      out.write("                <p>Quantity: <span readonly>1</span></p>\n");
      out.write("                <p>Price: ");
      out.print( formattedPrice );
      out.write("원</p> <!-- 포맷팅된 가격을 출력 -->\n");
      out.write("                <!-- 추가적으로 필요한 정보 출력 -->\n");
      out.write("                <input type=\"hidden\" name=\"productbrand\" value=\"");
      out.print( brand );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"productName\" value=\"");
      out.print( productName );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"price\" value=\"");
      out.print( price );
      out.write("\">\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        ");

                }
            }
        
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </tbody>\n");
      out.write("</table>\n");
      out.write("<!-- Purchase 버튼 -->\n");
      out.write("<input class=\"purchase-button\" type=\"button\" value=\"Purchase\" onclick=\"confirmPurchase()\">\n");
      out.write("<script>\n");
      out.write("    // 확인 창을 띄우고 사용자의 응답 값을 hidden 필드에 설정하는 함수\n");
      out.write("    function confirmPurchase() {\n");
      out.write("        var userResponse = confirm(\"구매하시겠습니까?\");\n");
      out.write("        if (userResponse) {\n");
      out.write("            // form을 submit\n");
      out.write("            document.getElementById(\"purchaseForm\").submit();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
