/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-27 10:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("file:/usr/local/tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1704443287000L));
    _jspx_dependants.put("jar:file:/usr/local/tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/page/../include/footer.jsp", Long.valueOf(1706519642000L));
    _jspx_dependants.put("/page/../include/navbar.jsp", Long.valueOf(1706575250000L));
    _jspx_dependants.put("/common/bootstrap_common.jsp", Long.valueOf(1706519642000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
// ServletContext를 사용하여 업로드 경로를 가져옴
   request.setCharacterEncoding("UTF-8");
   ServletContext context = request.getServletContext();
   String uploadPath = context.getRealPath("/images"); 
	
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>아디다스</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/main.css\">\n");
      out.write("\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/177bef69e2.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- \n");
      out.write("	css나 js 파일명에 min이 있는 것과 없는 것 차이점\n");
      out.write("	통상 js도 보안적인 이슈 때문에 소스를 분리해서 관리 배포(재사용성, 유지보수) 하게 되었다\n");
      out.write("	실제 페이지가 렌더링 되기 전에 다운로드가 된 후에 실행이되는 구조를 갖는다\n");
      out.write("	여백, 공백, 들여쓰기, 등이 포함되면 파일의 크기가 커진다\n");
      out.write("	여백, 공백, 들여쓰기 등을 다 생략하고 바짝 붙여서 코드가 작성된 버전이다.\n");
      out.write(" -->");
      out.write("\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: 'Arial', sans-serif;\n");
      out.write("	background-color: #F8F9FA;\n");
      out.write("	padding: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("	color: #343A40;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-list {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: wrap;\n");
      out.write("	justify-content: center;\n");
      out.write("	gap: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-card {\n");
      out.write("	border: 1px solid #DEE2E6;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	overflow: hidden;\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("	background-color: #FFFFFF;\n");
      out.write("	transition: transform 0.3s ease-in-out;\n");
      out.write("	width: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-card:hover {\n");
      out.write("	transform: scale(1.05);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-image {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 150px;\n");
      out.write("	object-fit: cover;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-info {\n");
      out.write("	padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-name {\n");
      out.write("	font-size: 18px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-description {\n");
      out.write("	font-size: 14px;\n");
      out.write("	color: #495057;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("	<!-- ============================== [[ NavBar section]] ==============================-->\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("    <!-- ============================== [[ NavBar section]] ==============================-->\n");
      out.write("    <script>\n");
      out.write("	    function main() {\n");
      out.write("	        document.getElementById(\"toMain\").submit();\n");
      out.write("    }\n");
      out.write("	</script>\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\" onclick=\"main()\">신발 가게</a>\n");
      out.write("        <form id=\"toMain\" name=\"goMain\" action=\"main.do\" method=\"post\">\n");
      out.write("	    	<!-- 메인으로 -->\n");
      out.write("		</form>\n");
      out.write("        <button\n");
      out.write("          class=\"navbar-toggler\"\n");
      out.write("          type=\"button\"\n");
      out.write("          data-bs-toggle=\"collapse\"\n");
      out.write("          data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("          aria-controls=\"navbarSupportedContent\"\n");
      out.write("          aria-expanded=\"false\"\n");
      out.write("          aria-label=\"Toggle navigation\"\n");
      out.write("        >\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("          <ul class=\"navbar-nav me-auto mb-4 mb-lg-0\">\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"menu1.do\">전체 상품</a>\n");
      out.write("            </li>\n");
      out.write("	        <li class=\"nav-item\">\n");
      out.write("	          <a class=\"nav-link\" href=\"menu2.do\">Nike</a>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"nav-item\">\n");
      out.write("	          <a class=\"nav-link\" href=\"menu3.do\">Adidas</a>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"nav-item\">\n");
      out.write("	          <a class=\"nav-link\" href=\"menu4.do\">Mschf</a>\n");
      out.write("	        </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("    <!-- ============================== [[ NavBar section]] ============================== -->");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ NavBar section]] ==============================-->\n");
      out.write("	<hr>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<h1>아디다스</h1>\n");
      out.write("		<hr>\n");
      out.write("		<div class=\"brand-list\">\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<hr>\n");
      out.write("		<hr>\n");
      out.write("	</div>\n");
      out.write("	<hr>\n");
      out.write("	<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("	");
      out.write("\n");
      out.write("    <!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("    <footer style=\"background-color: #000000; color: #ffffff\">\n");
      out.write("	  <div class=\"navbar navbar-expand-sm bg-dark justify-content-center\">\n");
      out.write("	    <a class=\"navbar-brand\"  style=\"color:white\">쌈뽕한 신발가게<br>\n");
      out.write("	    Copyright &copy;2024</a>\n");
      out.write("	  </div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("    ");
      out.write("\n");
      out.write("	<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /page/menu3.jsp(82,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/page/menu3.jsp(82,3) '${list03}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list03}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /page/menu3.jsp(82,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("				<a href=\"brandDetail.do?proname=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.proname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"brand-card\">\n");
            out.write("					<img class=\"brand-image\"\n");
            out.write("					src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.imagename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("					alt=\"Brand Image\">\n");
            out.write("					<div class=\"brand-info\">\n");
            out.write("						<div class=\"brand-description\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.proname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("					</div>\n");
            out.write("				</a>\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
