/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 09:11:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/member/../include/header.jsp", Long.valueOf(1708333857000L));
    _jspx_dependants.put("/member/../include/footer.jsp", Long.valueOf(1708333857000L));
    _jspx_dependants.put("/member/../include/sidemenu.jsp", Long.valueOf(1707962972000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Login</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all2.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/login.css\">\n");
      out.write("<!-- 인터넷 창 아이콘에 로고 나오게 하기 -->\n");
      out.write("<link rel=\"icon\" href=\"./images/CompanyLogo.png\">\n");
      out.write("</head>\n");
      out.write("<body class=\"nav-expended\">\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	");
      out.write('\n');
      out.write('\n');

// 세션을 가져옵니다.
// session2는 로그인용
HttpSession session2 = request.getSession();
// 세션에 저장된 사용자 정보가 있는지 확인합니다.
boolean reg = (session2 != null && session.getAttribute("user") != null);

      out.write("\n");
      out.write("<header>\n");
      out.write("	<div class=\"site-header\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"site-logo\">\n");
      out.write("				<h1>\n");
      out.write("					<a href=\"main.do\"> <img src=\"./images/CompanyLogo.png\" alt=\"로고\"\n");
      out.write("						class=\"logo-img\" width=\"200px\" height=\"100px\">\n");
      out.write("					</a>\n");
      out.write("				</h1>\n");
      out.write("			</div>\n");
      out.write("			<ul\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-statelogoff user-menu\">\n");
      out.write("				");
 if (reg) { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"logout.do\"><b>Logout</b></a></li>\n");
      out.write("				");
 } else { 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\"><b>Login</b></a></li>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("				<li class=\"menu-item\"><a href=\"myPage.do\"><b>MyPage</b></a></li>\n");
      out.write("				<li class=\"menu-item menu--cart\"><a href=\"cart.do\"><b>Cart</b><span\n");
      out.write("						class=\"badge displaynone\">()</span></a></li>\n");
      out.write("			</ul>\n");
      out.write("			<div class=\"hamburger\" role=\"button\" aria-expanded=\"false\">\n");
      out.write("				<span class=\"patty\"> </span>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"mobile-cart\">\n");
      out.write("				<a href=\"/order/basket.html\"><span class=\"badge\"></span></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("	<div class=\"site-main\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("\n");
      out.write("			");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/177bef69e2.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<div class=\"site-nav sidebar fixed\">\n");
      out.write("	<div class=\"nav-col col-left\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"about.do\">About us</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"xans-element- xans-layout xans-layout-category site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"best100.do\">BEST 100</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"all_in_one.do\">All-in-one</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"outer.do\">Outer</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"topshort.do\">Top(short sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"toplong.do\">Top(long sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bottoms.do\">Bottoms</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bags.do\">Bags</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"accessories.do\">Accessories</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"shoes.do\">Shoes</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"women.do\">Women only</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"nav-col col-right\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-statelogoff user-menu \">\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\">Login</a></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"/member/login.html?noMemberOrder&amp;returnUrl=%2Fmyshop%2Forder%2Flist.html\">Mypage</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.youtube.com/channel/UCNzODSZC2sraPyh4lDMQhpQ?view_as=subscriber\"\n");
      out.write("					target=\"_blank\">YouTube</a>&nbsp;<i class=\"fa-brands fa-youtube\"></i></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.instagram.com/faderoom_official/\" target=\"_blank\">Instagram</a>&nbsp;<i\n");
      out.write("					class=\"fa-brands fa-instagram\"></i></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"notice.do\">Notice</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"review.do\">Review</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"qna.do\">Q&amp;A</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"faq.do\">FAQ</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"cs-info\">\n");
      out.write("			<ul>\n");
      out.write("				<li>Counseling Center <br>02 123 4567\n");
      out.write("				</li>\n");
      out.write("				<li>13:00 - 18:00 <br>sat.sun.holiday off\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<form id=\"searchBarForm\" name=\"\" action=\"search.do\"\n");
      out.write("			method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\n");
      out.write("			<input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\">\n");
      out.write("			<div\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-searchside search-bar \">\n");
      out.write("				<!--\n");
      out.write("	                    $search_page = /product/search.html\n");
      out.write("	                    $product_page = /product/detail.html\n");
      out.write("	                -->\n");
      out.write("				<fieldset>\n");
      out.write("					<legend>검색</legend>\n");
      out.write("					<input id=\"keyword\" name=\"keyword\" fw-filter=\"\" fw-label=\"검색어\"\n");
      out.write("						fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\"\n");
      out.write("						onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\" value=\"\"\n");
      out.write("						type=\"text\"><input type=\"image\"\n");
      out.write("						src=\"./images/search-icon.png\" alt=\"검색\"\n");
      out.write("						onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\">\n");
      out.write("				</fieldset>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("			<div class=\"main\">\n");
      out.write("\n");
      out.write("				<!-- 여기서 부터 작성 -->\n");
      out.write("				<div class=\"entry-page\">\n");
      out.write("					<form id=\"member_form\" name=\"\" action=\"whologin.do\" method=\"post\">\n");
      out.write("\n");
      out.write("						<div class=\"xans-element- xans-member xans-member-login login \">\n");
      out.write("							<div class=\"login-header\">\n");
      out.write("								<h2>LOGIN</h2>\n");
      out.write("							</div>\n");
      out.write("							<fieldset>\n");
      out.write("								<legend>회원로그인</legend>\n");
      out.write("								<div class=\"form-field\">\n");
      out.write("									<label for=\"userId\">ID</label> <input id=\"userId\" name=\"userId\"\n");
      out.write("										fw-filter=\"isFill\" fw-label=\"아이디\" fw-msg=\"\"\n");
      out.write("										class=\"inputTypeText\" placeholder=\"\" value=\"\" type=\"text\"\n");
      out.write("										required>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-field\">\n");
      out.write("									<label for=\"userPasswd\">PASSWORD</label> <input id=\"userPasswd\"\n");
      out.write("										name=\"userPasswd\"\n");
      out.write("										fw-filter=\"isFill&amp;isMin[4]&amp;isMax[16]\" fw-label=\"패스워드\"\n");
      out.write("										fw-msg=\"\" autocomplete=\"off\" value=\"\" type=\"password\" required>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"login-footer\">\n");
      out.write("									<div class=\"login-extras\">\n");
      out.write("										<a href=\"findId.do\">아이디 찾기</a> <a href=\"findPasswd.do\">비밀번호\n");
      out.write("											찾기</a>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"login-actions\">\n");
      out.write("										<input type=\"submit\" value=\"Login\" class=\"primary-button\"\n");
      out.write("											style=\"margin: 0 auto;\">\n");
      out.write("										<!-- <a href=\"#none\" class=\"primary-button\"\n");
      out.write("											onclick=\"MemberAction.login('member_form'); return false;\"><span>Login</span></a> -->\n");
      out.write("										<a href=\"memberJoin.do\" class=\"primary-button\"><span>Join</span></a>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</fieldset>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<script>\n");
      out.write("					// 아이디 유효성 검사 정규식\n");
      out.write("					const idRegex = /^[a-z0-9]{4,16}$/;\n");
      out.write("\n");
      out.write("					// 비밀번호 유효성 검사 정규식\n");
      out.write("					const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{4,16}$/;\n");
      out.write("\n");
      out.write("					document.getElementById('member_form').addEventListener('submit',function(e) {\n");
      out.write("							e.preventDefault(); // 기본 동작 중단\n");
      out.write("\n");
      out.write("							// 아이디와 비밀번호 입력값 가져오기\n");
      out.write("							const idField = document.getElementById('userId');\n");
      out.write("							const pwField = document.getElementById('userPasswd');\n");
      out.write("							const errorMessage = document.getElementById('error-message');\n");
      out.write("\n");
      out.write("							// 아이디와 비밀번호의 유효성 검사\n");
      out.write("							if (!idRegex.test(idField.value)) {\n");
      out.write("								 alert('아이디는 영문 소문자, 숫자로 4자 이상, 16자 이하여야만 합니다.');\n");
      out.write("								return;\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							if (!passwordRegex.test(pwField.value)) {\n");
      out.write("								alert('비밀번호는 영문 대소문자, 숫자, 특수문자 중 최소 하나 이상을 포함하여 4자 이상, 16자 이하여야 합니다.');\n");
      out.write("								return;\n");
      out.write("							}\n");
      out.write("\n");
      out.write("							// 유효성 검사 통과 시 폼 제출\n");
      out.write("							this.submit();\n");
      out.write("					});\n");
      out.write("\n");
      out.write("					 // Enter 키 이벤트 리스너 등록\n");
      out.write("				    document.addEventListener('keydown', function(e) {\n");
      out.write("				        if (e.key === 'Enter') {\n");
      out.write("				            // 아이디와 비밀번호 필드 값 가져오기\n");
      out.write("				            const idField = document.getElementById('userId');\n");
      out.write("				            const pwField = document.getElementById('userPasswd');\n");
      out.write("\n");
      out.write("				            // 값이 비어 있는지 확인하고 알림 창 띄우기\n");
      out.write("				            if (idField.value.trim() === '') {\n");
      out.write("				                alert('아이디는 필수 입력 값입니다.');\n");
      out.write("				                return;\n");
      out.write("				            }\n");
      out.write("\n");
      out.write("				            if (pwField.value.trim() === '') {\n");
      out.write("				                alert('비밀번호는 필수 입력 값입니다.');\n");
      out.write("				                return;\n");
      out.write("				            }\n");
      out.write("\n");
      out.write("				        }\n");
      out.write("				    });\n");
      out.write("				</script>\n");
      out.write("\n");
      out.write("				<!-- 여기까지 작성 -->\n");
      out.write("\n");
      out.write("				<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("				<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("\n");
      out.write("				");
      out.write(" \n");
      out.write("	<div class=\"site-footer\">\n");
      out.write("		<ul>\n");
      out.write("			<li>\n");
      out.write("				<span>Mak U Swag | CEO One Stone One Billion | Personal \n");
      out.write("				Info Manager Team 401 | Account No. 국민은행 12345678900 </span>\n");
      out.write("				<span>Email <a href=\"mailto:teamone401@makuswag.co.kr\" style=\"color: blue\">info@ssambbong.co.kr</a></span><br>\n");
      out.write("\n");
      out.write("			</li>\n");
      out.write("			<li><span>4 floor, Hankuk Tower, 78 Gil 8, Gangnamdae-ro, Gangnam-gu, Seoul |</span> <span>Reg.\n");
      out.write("					No. 02-123-4567 |</span> <span>Ecommerce Reg. No.\n");
      out.write("					2023-SeoulJungnang-0207</span></li>\n");
      out.write("			<li class=\"legal-links\"><a href=\"agreement.do\"\n");
      out.write("				style=\"color: blue;\">Terms of Use</a> <a\n");
      out.write("				href=\"privacy.do\" style=\"color: blue;\">Privacy Policy</a>\n");
      out.write("				<p class=\"copyright\">© 2023 Mak U Swag</p></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
