/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-15 03:06:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/about/../include/header.jsp", Long.valueOf(1707962972000L));
    _jspx_dependants.put("/about/../include/cardanimation.jsp", Long.valueOf(1707900178000L));
    _jspx_dependants.put("/about/../include/sidemenu.jsp", Long.valueOf(1707962972000L));
    _jspx_dependants.put("/about/../include/kakaomap.jsp", Long.valueOf(1707800833000L));
    _jspx_dependants.put("/about/../include/footer.jsp", Long.valueOf(1707787815000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>About us</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<script type=\"module\" src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/cardanimation.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/all2.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/about.css\">\n");
      out.write("<link rel=\"icon\" href=\"./images/CompanyLogo.png\"> <!-- 인터넷 창 아이콘에 로고 나오게 하기 -->\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"nav-expended\">\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<header>\n");
      out.write("<div class=\"site-header\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"site-logo\">\n");
      out.write("			<h1>\n");
      out.write("				<a href=\"main.do\">\n");
      out.write("					<img src=\"./images/CompanyLogo.png\" alt=\"로고\" class=\"logo-img\" width=\"200px\" height=\"100px\">\n");
      out.write("				</a>\n");
      out.write("			</h1>\n");
      out.write("		</div>\n");
      out.write("		<ul class=\"xans-element- xans-layout xans-layout-statelogoff user-menu\">\n");
      out.write("			<li class=\"menu-item\"><a href=\"login.do\"><b>Login</b></a></li>\n");
      out.write("			<li class=\"menu-item\"><a href=\"myPage.do\"><b>MyPage</b></a></li>\n");
      out.write("			<li class=\"menu-item menu--cart\"><a href=\"cart.do\"><b>Cart</b><span class=\"badge displaynone\">()</span></a></li>\n");
      out.write("		</ul>\n");
      out.write("		<div class=\"hamburger\" role=\"button\" aria-expanded=\"false\">\n");
      out.write("			<span class=\"patty\">\n");
      out.write("			</span>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"mobile-cart\">\n");
      out.write("			<a href=\"/order/basket.html\"><span class=\"badge\"></span></a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("	<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("	<div class=\"site-main\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("\n");
      out.write("			");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/177bef69e2.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<div class=\"site-nav sidebar fixed\">\n");
      out.write("	<div class=\"nav-col col-left\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"about.do\">About us</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"xans-element- xans-layout xans-layout-category site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"best100.do\">BEST 100</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"all_in_one.do\">All-in-one</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"outer.do\">Outer</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"topshort.do\">Top(short sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"toplong.do\">Top(long sleeve)</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bottoms.do\">Bottoms</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"bags.do\">Bags</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"accessories.do\">Accessories</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"shoes.do\">Shoes</a></li>\n");
      out.write("				<li class=\"menu-item xans-record-\"><a href=\"women.do\">Women only</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"nav-col col-right\">\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-statelogoff user-menu \">\n");
      out.write("				<li class=\"menu-item\"><a href=\"login.do\">Login</a></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"/member/login.html?noMemberOrder&amp;returnUrl=%2Fmyshop%2Forder%2Flist.html\">Mypage</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.youtube.com/channel/UCNzODSZC2sraPyh4lDMQhpQ?view_as=subscriber\"\n");
      out.write("					target=\"_blank\">YouTube</a>&nbsp;<i class=\"fa-brands fa-youtube\"></i></li>\n");
      out.write("				<li class=\"menu-item\"><a\n");
      out.write("					href=\"https://www.instagram.com/faderoom_official/\" target=\"_blank\">Instagram</a>&nbsp;<i\n");
      out.write("					class=\"fa-brands fa-instagram\"></i></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"site-menu\">\n");
      out.write("			<ul>\n");
      out.write("				<li class=\"menu-item\"><a href=\"notice.do\">Notice</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"review.do\">Review</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"qna.do\">Q&amp;A</a></li>\n");
      out.write("				<li class=\"menu-item\"><a href=\"faq.do\">FAQ</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"cs-info\">\n");
      out.write("			<ul>\n");
      out.write("				<li>Counseling Center <br>02 123 4567\n");
      out.write("				</li>\n");
      out.write("				<li>13:00 - 18:00 <br>sat.sun.holiday off\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<form id=\"searchBarForm\" name=\"\" action=\"search.do\"\n");
      out.write("			method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\n");
      out.write("			<input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\">\n");
      out.write("			<div\n");
      out.write("				class=\"xans-element- xans-layout xans-layout-searchside search-bar \">\n");
      out.write("				<!--\n");
      out.write("	                    $search_page = /product/search.html\n");
      out.write("	                    $product_page = /product/detail.html\n");
      out.write("	                -->\n");
      out.write("				<fieldset>\n");
      out.write("					<legend>검색</legend>\n");
      out.write("					<input id=\"keyword\" name=\"keyword\" fw-filter=\"\" fw-label=\"검색어\"\n");
      out.write("						fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\"\n");
      out.write("						onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\" value=\"\"\n");
      out.write("						type=\"text\"><input type=\"image\"\n");
      out.write("						src=\"./images/search-icon.png\" alt=\"검색\"\n");
      out.write("						onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\">\n");
      out.write("				</fieldset>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<div class=\"main\">\n");
      out.write("\n");
      out.write("				<!-- 여기서 부터 작성 -->\n");
      out.write("				\n");
      out.write("				<div class=\"about\">\n");
      out.write("	\n");
      out.write("					<div class=\"manifesto\">\n");
      out.write("						<span class=\"site-logo\">\n");
      out.write("							<h1 style=\"text-align: center;\">\n");
      out.write("								<a href=\"main.do\">\n");
      out.write("									<img src=\"./images/CompanyLogo.png\" alt=\"로고\" class=\"logo-img\" width=\"200px\" height=\"100px\">\n");
      out.write("								</a>\n");
      out.write("							</h1>\n");
      out.write("						</span>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						<p>Mak U Swag은 가장 개인적인 공간에서 전개되는 캐주얼 셀렉샵입니다.</p>\n");
      out.write("						<p>단순 셀러로서가 아닌 인테리어, 디자인, 포토, 스타일링등 전체적인 조화를 추구하는 갤러리 스토어입니다.</p>\n");
      out.write("						<p>개인의 취향이 가득 담긴 공간으로 패션을 사랑하는 분들이라면 누구나 편하게 즐길 수 있습니다.</p>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						\n");
      out.write("						<div class=\"about-photos\">\n");
      out.write("							<img src=\"./images/about/about-photo-1.jpg\" alt=\"1\" width=\"1132px\" height=\"754px\" style=\"text-align: center;\">&nbsp;\n");
      out.write("							<br>\n");
      out.write("							<img src=\"./images/about/about-photo-2.jpg\" alt=\"2\">&nbsp;\n");
      out.write("							<br>\n");
      out.write("							<img src=\"./images/about/about-photo-3.jpg\" alt=\"3\">&nbsp;\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<!-- 크루 소개 -->\n");
      out.write("						<h1 style=\"text-align: center;\">Crew</h1>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						\n");
      out.write("						");
      out.write("\n");
      out.write("<div class=\"content2\">\n");
      out.write("	<div class=\"possibilities\">\n");
      out.write("		<div class=\"option active\"\n");
      out.write("			style=\"--optionBackground: url(../images/member/LDG.jpg);\">\n");
      out.write("			<div class=\"shadow\"></div>\n");
      out.write("			<div class=\"label\">\n");
      out.write("				<div class=\"icon\">\n");
      out.write("					<i class=\"fa-solid fa-code\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"info\">\n");
      out.write("					<div class=\"main\">Daegeun Lee</div>\n");
      out.write("					<div class=\"sub\">Omuke trughte a otufta</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"option\"\n");
      out.write("			style=\"--optionBackground: url(../images/member/PJM.jpg);\">\n");
      out.write("			<div class=\"shadow\"></div>\n");
      out.write("			<div class=\"label\">\n");
      out.write("				<div class=\"icon\">\n");
      out.write("					<img alt=\"코딩\" src=\"./images/member/coding.png\" width=\"15\" height=\"13\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"info\">\n");
      out.write("					<div class=\"main\">Jungmin Park</div>\n");
      out.write("					<div class=\"sub\">Omuke trughte a otufta</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"option\"\n");
      out.write("			style=\"--optionBackground: url(../images/member/PJH.jpg);\">\n");
      out.write("			<div class=\"shadow\"></div>\n");
      out.write("			<div class=\"label\">\n");
      out.write("				<div class=\"icon\">\n");
      out.write("					<i class=\"fa-brands fa-square-js\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"info\">\n");
      out.write("					<div class=\"main\">Jihwan Park</div>\n");
      out.write("					<div class=\"sub\">Omuke trughte a otufta</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"option\"\n");
      out.write("			style=\"--optionBackground: url(../images/member/JSJ.jpg);\">\n");
      out.write("			<div class=\"shadow\"></div>\n");
      out.write("			<div class=\"label\">\n");
      out.write("				<div class=\"icon\">\n");
      out.write("					<i class=\"fa-solid fa-file-code\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"info\">\n");
      out.write("					<div class=\"main\">Sungjin Jin</div>\n");
      out.write("					<div class=\"sub\">Omuke trughte a otufta</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<script type=\"text/javascript\" src=\"./js/index.js\"></script>\n");
      out.write("						<!-- 크루 소개 -->\n");
      out.write("						\n");
      out.write("						<br>\n");
      out.write("						<hr>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						<br>\n");
      out.write("						\n");
      out.write("						<!-- 카카오 지도 Api  -->\n");
      out.write("						\n");
      out.write("						");
      out.write("\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=48780f73936ef8fc317d37ebe0bd09ff\"></script>\n");
      out.write("<style>\n");
      out.write(".panel {\n");
      out.write("	/* display: flex; */\n");
      out.write("	text-align: center;\n");
      out.write("	flex-direction: column;\n");
      out.write("	border: 1px solid #222;\n");
      out.write("	border-radius: 20px;\n");
      out.write("	padding: 10px;\n");
      out.write("	max-width: 1460px;\n");
      out.write("	/* min-height: 650px; */\n");
      out.write("	justify-content: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mapwrap {\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: space-around;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".map {\n");
      out.write("	max-width: 500px; /* 최대폭 */\n");
      out.write("	height: 400px; /* 지도가 표시될 높이 */\n");
      out.write("	width: 100%; /* 화면 전체를 100 */\n");
      out.write("	margin-bottom: 20px; /* 아래쪽 외부여백을 위아래 20px 띄어줌 */\n");
      out.write("	border: 2px solid lightgray; /* 테두리선 두께 2px 실선 선색상 */\n");
      out.write("	border-radius: 20px; /* 모서리 20px 굴려줌 */\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<div class=\"panel\">\n");
      out.write("	<div>\n");
      out.write("		<h2>\n");
      out.write("			<b>Mak U Swag</b>\n");
      out.write("		</h2>\n");
      out.write("	</div>\n");
      out.write("	<hr style=\"height: 2px\" />\n");
      out.write("	<div>\n");
      out.write("		<h3>\n");
      out.write("			<b>찾아오시는 곳</b>\n");
      out.write("		</h3>\n");
      out.write("	</div>\n");
      out.write("	<hr style=\"height: 2px\" />\n");
      out.write("	<div class=\"mapwrap\">\n");
      out.write("		<div id=\"map\" class=\"map\"></div>\n");
      out.write("		<!-- <div id=\"map\" style=\"width:500px;height:400px;\"></div> -->\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("					//console.log(document.getElementById(\"map\"));\n");
      out.write("					//document.querySelector(\"#map\");\n");
      out.write("					const container = document.getElementById('map'); //지도를 담을 영역의 DOM 레퍼런스\n");
      out.write("					//배열 선언 - 마커를 여러개 표시하고 싶은 경우일때 참고\n");
      out.write("					//자바스크립트 배열 복습 -> 깊은복사(새로운 배열 생성해서 사용함)와 얕은 복사(원본사용함)\n");
      out.write("					const positions = [ {\n");
      out.write("						content : \"<div style='padding: 5px; text-align: center;'><h5>Mak U Swag</h5><img src='./images/CompanyLogo.png' alt='로고' class='logo-img' width='150px' height='150px'></div>\",\n");
      out.write("						latlng : new kakao.maps.LatLng(37.494708, 127.030082)\n");
      out.write("					} ];\n");
      out.write("					const options = { //지도를 생성할 때 필요한 기본 옵션\n");
      out.write("						center : positions[0].latlng,\n");
      out.write("						level : 4\n");
      out.write("					//지도의 레벨(확대, 축소 정도)\n");
      out.write("					};\n");
      out.write("					const map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴\n");
      out.write("\n");
      out.write("					//제목: 카카오 맵에 마커 표시하기\n");
      out.write("					// 지도를 클릭한 위치에 표출할 마커입니다\n");
      out.write("					const marker = new kakao.maps.Marker({\n");
      out.write("						map : map, //마커를 표시할 지도\n");
      out.write("						// 지도 중심좌표에 마커를 생성합니다 \n");
      out.write("						position : positions[0].latlng\n");
      out.write("					//마커의 위치 잡아주기\n");
      out.write("					});\n");
      out.write("					// 마커에 표시할 인포윈도우를 생성하기\n");
      out.write("					const infoWindow = new kakao.maps.InfoWindow({\n");
      out.write("						//생성자 안에 좌중괄호 우중괄호를 붙이면 실행문 작성 가능함\n");
      out.write("						content : positions[0].content\n");
      out.write("					//인포윈도우(다이얼로그창, 팝업창)에 표시할 내용\n");
      out.write("					});//아래코드에서 클로저를 사용할 때는 반드시 세미콜론 붙일 것.\n");
      out.write("\n");
      out.write("					// 마커에 이벤트를 등록하는 함수 구현\n");
      out.write("					// 구현하는 즉시 실행시키기 위해서 클로저 사용함\n");
      out.write("					(function(marker, infoWindow) {\n");
      out.write("						//마커에 mouseover 이벤트를 등록하고 마우스 오버시에 인포윈도우를 표시함\n");
      out.write("						//@param:marker는 이벤트 소스이다\n");
      out.write("						//@param:marker에 적용할 수 있는 이벤트 핸들러 이름임\n");
      out.write("						//@param:콜백함수-네가 마커에 마우스 오버 시키면 내가 실행을 약속할께 \n");
      out.write("						kakao.maps.event.addListener(marker, 'mouseover',\n");
      out.write("								function() {\n");
      out.write("									infoWindow.open(map, marker);\n");
      out.write("								});\n");
      out.write("						//마커에 mouseout 이벤트를 등록하고 마우스 아웃시에 인포윈도우를 닫음\n");
      out.write("						kakao.maps.event.addListener(marker, 'mouseout',\n");
      out.write("								function() {\n");
      out.write("									infoWindow.close();\n");
      out.write("								});\n");
      out.write("					})(marker, infoWindow);//여기 괄호가 함수를 호출하는 코드임\n");
      out.write("\n");
      out.write("					// 지도에 마커를 표시합니다\n");
      out.write("					marker.setMap(map);\n");
      out.write("				</script>\n");
      out.write("	</div>\n");
      out.write("	<hr style=\"height: 2px\" />\n");
      out.write("	<table class=\"table\" style=\"minWidth: 700px; border: 1px solid black;\">\n");
      out.write("		<tbody style=\"border: 1px solid black\">\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h3>주소</h3></b></td>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h4>서울특별시 강남구 강남대로 78길 8 한국빌딩 4층 (T: 02-123-4567)</h4></b></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h3>버스</h3></b></td>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h4>강남역 정류장 지선 9202 일반 4312</h4></b></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h3>지하철</h3></b></td>\n");
      out.write("				<td style=\"border-bottom: 1px solid black\"><b><h4>지하철 2호선 강남역 4번출구 200m</h4></b></td>\n");
      out.write("			</tr>\n");
      out.write("		</tbody>\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("						\n");
      out.write("						<!-- 카카오 지도 Api  -->\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<!-- 여기까지 작성 -->\n");
      out.write("				\n");
      out.write("			<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("			<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("	<div class=\"site-footer\">\n");
      out.write("		<ul>\n");
      out.write("			<li>\n");
      out.write("				<span>Mak U Swag | CEO One Stone One Billion | Personal \n");
      out.write("				Info Manager Team 401 | Account No. 국민은행 12345678900 </span>\n");
      out.write("				<span>Email <a href=\"mailto:teamone401@makuswag.co.kr\" style=\"color: blue\">info@ssambbong.co.kr</a></span><br>\n");
      out.write("\n");
      out.write("			</li>\n");
      out.write("			<li><span>4 floor, Hankuk Tower, 78 Gil 8, Gangnamdae-ro, Gangnam-gu, Seoul |</span> <span>Reg.\n");
      out.write("					No. 02-123-4567 |</span> <span>Ecommerce Reg. No.\n");
      out.write("					2023-SeoulJungnang-0207</span></li>\n");
      out.write("			<li class=\"legal-links\"><a href=\"agreement.do\"\n");
      out.write("				style=\"color: blue;\">Terms of Use</a> <a\n");
      out.write("				href=\"privacy.do\" style=\"color: blue;\">Privacy Policy</a>\n");
      out.write("				<p class=\"copyright\">© 2023 Mak U Swag</p></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
