/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 08:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.google.gson.Gson;
import java.util.ArrayList;

public final class Gender_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("<style>\n");
      out.write("body, html {\n");
      out.write("    height: 100%;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".chart-container {\n");
      out.write("    width: 120%;\n");
      out.write("    height: 80vh; /* 차트 컨테이너의 높이 설정 */\n");
      out.write("    margin-right: 20px;\n");
      out.write("    margin-left: -10%;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".canvas-container {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("canvas {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"chart-container\">\n");
      out.write("    <div class=\"canvas-container\">\n");
      out.write("        <canvas id=\"myChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");

    ArrayList<String> labels1 = (ArrayList<String>) session.getAttribute("labels1");
    ArrayList<Integer> data1 = (ArrayList<Integer>) session.getAttribute("data1"); 
    ArrayList<Integer> data2 = (ArrayList<Integer>) session.getAttribute("data2");
  
    // JSON 형식으로 데이터를 만듭니다.
    String jsonData = new Gson().toJson(data1);
    String jsonData2 = new Gson().toJson(data2);

      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // JSON 형식의 데이터를 JavaScript 변수에 할당\n");
      out.write("    const labels1 = ");
      out.print( new Gson().toJson(labels1) );
      out.write(";\n");
      out.write("    const data1 = ");
      out.print( jsonData );
      out.write(";\n");
      out.write("    const data2 = ");
      out.print( jsonData2 );
      out.write(";\n");
      out.write("\n");
      out.write("    // 성별 비율을 계산하여 데이터셋 생성\n");
      out.write("    const total = data1[1] + data2[0]; // 전체 인원 수 계산\n");
      out.write("    const malePercentage = (data1[1] / total) * 100; // 남성 비율 계산\n");
      out.write("    const femalePercentage = (data2[0] / total) * 100; // 여성 비율 계산\n");
      out.write("\n");
      out.write("    // 차트 생성\n");
      out.write("    const ctx = document.getElementById('myChart');\n");
      out.write("    new Chart(ctx, {\n");
      out.write("        type: 'pie',\n");
      out.write("        data: {\n");
      out.write("            labels: ['남자', '여자'], // 세션에서 가져온 라벨 설정\n");
      out.write("            datasets: [{\n");
      out.write("                label: '성별 비율',\n");
      out.write("                data: [malePercentage, femalePercentage], // 비율 데이터 입력\n");
      out.write("                backgroundColor: [\n");
      out.write("                    'rgba(54, 162, 235, 0.5)',\n");
      out.write("                    'rgba(255, 99, 132, 0.5)'\n");
      out.write("                ],\n");
      out.write("                borderColor: [\n");
      out.write("                    'rgba(54, 162, 235, 1)',\n");
      out.write("                    'rgba(255, 99, 132, 1)'\n");
      out.write("                ],\n");
      out.write("                borderWidth: 1 // 선 제거\n");
      out.write("            }]\n");
      out.write("        },\n");
      out.write("        options: {\n");
      out.write("            maintainAspectRatio: 2,\n");
      out.write("            plugins: {\n");
      out.write("                legend: {\n");
      out.write("                    // 위치 설정 등 legend 옵션 추가\n");
      out.write("                },\n");
      out.write("                tooltips: {\n");
      out.write("                    enabled: false // 도구 팁 제거\n");
      out.write("                },\n");
      out.write("                title: {\n");
      out.write("                    display: true,\n");
      out.write("                    text: '가입자 성별 비율', // 제목 추가\n");
      out.write("                    position: 'top' // 제목 위치 설정\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            scales: {\n");
      out.write("                x: {\n");
      out.write("                    display: false // x축 라벨과 축 라인 제거\n");
      out.write("                },\n");
      out.write("                y: {\n");
      out.write("                    display: false // y축 라벨과 축 라인 제거\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
