/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 08:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.google.gson.Gson;

public final class Manager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("<style>\n");
      out.write(" body {\n");
      out.write("            font-size: 14px; /* 기본 폰트 크기 */\n");
      out.write("        }\n");
      out.write(" @media screen and (max-width: 768px) {\n");
      out.write("            /* 화면 너비가 768px 이하일 때 적용되는 스타일 */\n");
      out.write("            /* 예시: 너비가 축소되면 폰트 크기를 줄입니다. */\n");
      out.write("            body {\n");
      out.write("                font-size: 14px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("* {\n");
      out.write("    z-index: 3;\n");
      out.write("}\n");
      out.write("#managerFrame {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<button id=\"DayButton\">일별</button>\n");
      out.write("<button id=\"MonthButton\">월별</button>\n");
      out.write("<button id=\"YearButton\">연별</button>\n");
      out.write("<script>\n");
      out.write("    // 세션에서 가져온 labels와 data 데이터가 null인지 확인\n");
      out.write("    // JSON 형식의 데이터를 JavaScript 변수에 할당\n");
      out.write("    \n");
      out.write("    // JSON 형식의 데이터를 JavaScript 변수에 할당\n");
      out.write("    \n");
      out.write("    // 일별 버튼 클릭 이벤트 리스너\n");
      out.write("    document.getElementById('DayButton').addEventListener('click', function() {\n");
      out.write("        console.log('일별 버튼 클릭');\n");
      out.write("        // Manager.jsp에 있는 iframe의 src 변경\n");
      out.write("        const managerIframe = document.getElementById('managerFrame');\n");
      out.write("        if (managerIframe) {\n");
      out.write("            managerIframe.src = \"Managerday.jsp\";\n");
      out.write("        } else {\n");
      out.write("            console.error(\"Manager.jsp iframe을 찾을 수 없습니다.\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("   \n");
      out.write("    // 월별 버튼 클릭 이벤트 리스너\n");
      out.write("    document.getElementById('MonthButton').addEventListener('click', function() {\n");
      out.write("        console.log('월별 버튼 클릭');\n");
      out.write("        // Manager.jsp에 있는 iframe의 src 변경\n");
      out.write("        const managerIframe = document.getElementById('managerFrame');\n");
      out.write("        if (managerIframe) {\n");
      out.write("            managerIframe.src = \"ManagerMonth.jsp\";\n");
      out.write("        } else {\n");
      out.write("            console.error(\"Manager.jsp iframe을 찾을 수 없습니다.\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // 연별 버튼 클릭 이벤트 리스너\n");
      out.write("    document.getElementById('YearButton').addEventListener('click', function() {\n");
      out.write("        console.log('연별 버튼 클릭');\n");
      out.write("        // Manager.jsp에 있는 iframe의 src 변경\n");
      out.write("        const managerIframe = document.getElementById('managerFrame');\n");
      out.write("        if (managerIframe) {\n");
      out.write("            managerIframe.src = \"ManagerYear.jsp\";\n");
      out.write("        } else {\n");
      out.write("            console.error(\"Manager.jsp iframe을 찾을 수 없습니다.\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<iframe id=\"managerFrame\" src=\"\" frameborder=\"0\" style=\"width: 100%; height: 500px;\"></iframe>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
