/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 08:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.google.gson.Gson;
import java.util.ArrayList;

public final class ProductPer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Pie Chart</title>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        body, html {\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .chart-container {\n");
      out.write("    width: 113%;\n");
      out.write("    height: 80vh; /* 차트 컨테이너의 높이 설정 */\n");
      out.write("    margin-right: 20px;\n");
      out.write("    margin-left: -10%;\n");
      out.write("\n");
      out.write("        .canvas-container {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        canvas {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"chart-container\">\n");
      out.write("        <div class=\"canvas-container\">\n");
      out.write("            <canvas id=\"myChart\"></canvas>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  ");

    ArrayList<String> labels5 = (ArrayList<String>) session.getAttribute("labels5");
    ArrayList<Integer> data6 = (ArrayList<Integer>) session.getAttribute("data6"); 

      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // JSON 형식의 데이터를 JavaScript 변수에 할당\n");
      out.write("    const labels5 = ");
      out.print( new Gson().toJson(labels5) );
      out.write(";\n");
      out.write("    const data6 = ");
      out.print( new Gson().toJson(data6) );
      out.write(";\n");
      out.write("\n");
      out.write("    // 전체 판매 갯수 계산\n");
      out.write("    const totalQuantity = data6.reduce((acc, cur) => acc + cur, 0);\n");
      out.write("\n");
      out.write("    // 각 상품의 판매 비율 계산 및 퍼센트로 변환\n");
      out.write("    const percentages = data6.map(quantity => ((quantity / totalQuantity) * 100).toFixed(2) + '%');\n");
      out.write("\n");
      out.write("    // 차트 생성\n");
      out.write("    const ctx = document.getElementById('myChart').getContext('2d');\n");
      out.write("    new Chart(ctx, {\n");
      out.write("        type: 'pie',\n");
      out.write("        data: {\n");
      out.write("            labels: labels5,\n");
      out.write("            datasets: [{\n");
      out.write("                label: '상품별 판매 비율',\n");
      out.write("                data: data6,\n");
      out.write("                backgroundColor: [\n");
      out.write("                    'rgba(255, 99, 132, 0.2)',\n");
      out.write("                    'rgba(54, 162, 235, 0.2)',\n");
      out.write("                    'rgba(255, 206, 86, 0.2)',\n");
      out.write("                    'rgba(75, 192, 192, 0.2)',\n");
      out.write("                    'rgba(153, 102, 255, 0.2)',\n");
      out.write("                    'rgba(255, 159, 64, 0.2)'\n");
      out.write("                ],\n");
      out.write("                borderColor: [\n");
      out.write("                    'rgba(255, 99, 132, 1)',\n");
      out.write("                    'rgba(54, 162, 235, 1)',\n");
      out.write("                    'rgba(255, 206, 86, 1)',\n");
      out.write("                    'rgba(75, 192, 192, 1)',\n");
      out.write("                    'rgba(153, 102, 255, 1)',\n");
      out.write("                    'rgba(255, 159, 64, 1)'\n");
      out.write("                ],\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        },\n");
      out.write("        options: {\n");
      out.write("            responsive: false,\n");
      out.write("            plugins: {\n");
      out.write("                tooltip: {\n");
      out.write("                    callbacks: {\n");
      out.write("                        label: function(context) {\n");
      out.write("                            var label = context.label || '';\n");
      out.write("                            var value = context.parsed || 0;\n");
      out.write("                            var percentage = (value / totalQuantity) * 100;\n");
      out.write("                            percentage = parseFloat(percentage).toFixed(2);\n");
      out.write("                            return label + ': ' + value + ' (' + percentage + '%)';\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                title: {\n");
      out.write("                    display: true,\n");
      out.write("                    text: '상품별 판매 비율',\n");
      out.write("                    position: 'top'\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
