/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-19 08:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.google.gson.Gson;
import java.util.ArrayList;

public final class UserManageAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/admin/../include/sidebar.jsp", Long.valueOf(1707900178000L));
    _jspx_dependants.put("/admin/UserManagehead.jsp", Long.valueOf(1707826857000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"icon\" href=\"./images/CompanyLogo.png\"> \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("    \n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"https://kit.fontawesome.com/896000ac05.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<style>\n");
      out.write("/* 노멀라이즈 시작 */\n");
      out.write("body, ul, li {\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  list-style: none;   /* 해당 태그의 list-style을 none으로 하는 것으로 ●을 제거한다 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("  color: inherit;   /* 부모 엘리먼트의 값을 물려받는다 */\n");
      out.write("  text-decoration: none;    /* 해당 태그의 text-decoration 속성을 none 값으로 하는 것으로 밑줄을 제거한다 */\n");
      out.write("}\n");
      out.write("/* 노멀라이즈 끝 */\n");
      out.write("\n");
      out.write("/* 커스텀 시작 */\n");
      out.write(".side-bar > ul ul {\n");
      out.write("  display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 사이트의 높이를 5000px로 만들어 스크롤 생성 */\n");
      out.write("body {\n");
      out.write("  height: 5000px;\n");
      out.write("  background-color: #FFFFFF;\n");
      out.write("  position: sticky;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 사이드바 시작 */\n");
      out.write("\n");
      out.write("/* 사이드바의 너비와 높이를 변수를 통해 통제 */\n");
      out.write(":root {\n");
      out.write("  --side-bar-width: 260px;\n");
      out.write("  --side-bar-height:75vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar {\n");
      out.write("  position: fixed;    /* 스크롤을 따라오도록 지정 */\n");
      out.write("  background-color: black;\n");
      out.write("  width: var(--side-bar-width);\n");
      out.write("  min-height: 85%;   /* 사이드바의 높이를 전체 화면 높이의 90%로 지정 */\n");
      out.write("  margin-top: 5%;    /* 사이드바 위와 아래의 마진을 동일하게 지정 */\n");
      out.write("  z-index: 1000;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 아이콘 시작 */\n");
      out.write(".side-bar__icon-box {\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: flex-end;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar__icon-1 {\n");
      out.write("  position: relative;\n");
      out.write("  width: 23px;\n");
      out.write("  height: 17px;\n");
      out.write("  margin: 15px;\n");
      out.write("  margin-top: 20px;\n");
      out.write("  transition: .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(":root {\n");
      out.write("  --side-bar__icon: .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar__icon-1 > div {\n");
      out.write("  position: absolute;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 20%;\n");
      out.write("  background-color: white;\n");
      out.write("  transition: all var(--side-bar__icon);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar__icon-1 > div:nth-of-type(1) {\n");
      out.write("  top: 0;\n");
      out.write("  width: auto;\n");
      out.write("  left: 0;\n");
      out.write("  right: 0;\n");
      out.write("  transition: all var(--side-bar__icon), left calc(var(--side-bar__icon) / 2) calc(var(--side-bar__icon) / 2), right calc(var(--side-bar__icon) / 2) calc(var(--side-bar__icon) / 2), height calc(var(--side-bar__icon) / 2) 0s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar__icon-1 > div:nth-of-type(2) {\n");
      out.write("  top: 40%;\n");
      out.write("  transform-origin:bottom left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar__icon-1 > div:nth-of-type(3) {\n");
      out.write("  top: 80%;\n");
      out.write("  left: auto;\n");
      out.write("  right: 0;\n");
      out.write("  transform-origin:bottom right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".side-bar:hover .side-bar__icon-1 {\n");
      out.write("  transform: translate(-198px, 0);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar:hover .side-bar__icon-1 > div:nth-of-type(2) {\n");
      out.write("  transform:rotate(45deg);\n");
      out.write("  width: 70.5%;\n");
      out.write("  height: 25%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar:hover .side-bar__icon-1 > div:nth-of-type(3) {\n");
      out.write("  top: 40%;\n");
      out.write("  transform:rotate(-45deg);\n");
      out.write("  width: 70.5%;\n");
      out.write("  height: 25%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar:hover .side-bar__icon-1 > div:nth-of-type(1) {\n");
      out.write("  left: 41%;\n");
      out.write("  right: 41%;\n");
      out.write("  height: 50%;\n");
      out.write("  transition: all var(--side-bar__icon), left calc(var(--side-bar__icon) / 2) 0s, right calc(var(--side-bar__icon) / 2) 0s, height calc(var(--side-bar__icon) / 2) calc(var(--side-bar__icon) / 2);\n");
      out.write("}\n");
      out.write("/* 아이콘 끝 */\n");
      out.write("\n");
      out.write("/* 모든 메뉴의 a에 속성값 부여 */\n");
      out.write("\n");
      out.write(".side-bar ul > li > a {\n");
      out.write("  display: block;\n");
      out.write("  color: white;\n");
      out.write("  font-size: 0.9rem; /* 텍스트 크기 조절 */\n");
      out.write("  font-weight: bold;\n");
      out.write("  padding-top:15px; /* 상단 패딩 조절 */\n");
      out.write("  padding-bottom: 15px; /* 하단 패딩 조절 */\n");
      out.write("  padding-left: 20%; /* 좌측 패딩 조절 */\n");
      out.write("  transition: .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".side-bar ul > li{\n");
      out.write("  display: block;\n");
      out.write("  color: white;\n");
      out.write("  font-size: 0.8rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 자식의 position이 absolute일 때 자식을 영역 안에 가두어 준다 */\n");
      out.write(".side-bar > ul > li {\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 모든 메뉴가 마우스 인식 시 반응 */\n");
      out.write(".side-bar ul > li:hover > a {\n");
      out.write("  background-color: #555;\n");
      out.write("  border-bottom: 1px solid #999;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 1차 메뉴의 항목이 마우스 인식 시에 2차 메뉴 등장 */\n");
      out.write(".side-bar > ul > li:hover > ul {\n");
      out.write("  display: block;\n");
      out.write("  position: absolute;\n");
      out.write("  background-color: #888;\n");
      out.write("  top: 0%;         /* 2차 메뉴의 상단을 1차 메뉴의 상단에 고정 */\n");
      out.write("  left: 100%;     /* 2차 메뉴를 1차 메뉴의 너비만큼 이동 */\n");
      out.write("  width: 70%;    /* 1차 메뉴의 너비를 상속 */\n");
      out.write("  padding:0px;\n");
      out.write("  margin:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 사이드바 너비의 80%만큼 왼쪽으로 이동 */\n");
      out.write(".side-bar {\n");
      out.write("  border-radius: 20px;\n");
      out.write("  transform: translate(calc(var(--side-bar-width) * -0.8), 0);\n");
      out.write("  transition: .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 마우스 인식 시 원래의 위치로 이동 */\n");
      out.write(".side-bar:hover {\n");
      out.write("  transform: translate(-20px, 0);   /* 둥근 모서리의 너비만큼 숨겨주기 */\n");
      out.write("}\n");
      out.write(".side-bar > ul ul {\n");
      out.write("  display: none;\n");
      out.write("  max-height: 230px; /* 원하는 높이로 조정하세요 */\n");
      out.write("  overflow-y: auto; /* 내용이 넘칠 경우 스크롤 표시 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* 사이드바 끝 */\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<aside class=\"side-bar\">\n");
      out.write("  <section class=\"side-bar__icon-box\">\n");
      out.write("    <section class=\"side-bar__icon-1\">\n");
      out.write("      <div></div>\n");
      out.write("      <div></div>\n");
      out.write("      <div></div>\n");
      out.write("    </section>\n");
      out.write("  </section>\n");
      out.write("  <ul>\n");
      out.write("    <li>\n");
      out.write("       <a href=\"#\"><i class=\"fa-solid fa-user\" style=\"color: white;\"> </i> 회원</a>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"manager.do\">회원관리</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <li>\n");
      out.write("      <a href=\"#\"><i class=\"fa-solid fa-gift\" style=\"color: white;\"></i> 상품</a>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"productmanager.do\">상품관리</a></li>\n");
      out.write("        <li><a href=\"productinsert.do\">상품등록</a></li>\n");
      out.write("        <li><a href=\"productupdate.do\">상품수정</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <li>\n");
      out.write("      <a href=\"#\"><i class=\"fa-solid fa-list\" style=\"color: white;\"></i> 게시판</a>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"noticemanager.do\">게시판 관리</a></li>\n");
      out.write("        <li><a href=\"noticeinsert.do\">게시판 작성</a></li>\n");
      out.write("        <li><a href=\"noticeupdate.do\">게시판 수정</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("    <li>\n");
      out.write("      <a href=\"totalmanager.do\"><i class=\"fa-solid fa-cart-plus\" style=\"color:white;\"></i> 매출</a>\n");
      out.write("    </li>\n");
      out.write("   <li><br><br><br><br><br><br> <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Counseling Center</span><br>\n");
      out.write("		<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;02 436 1009</span><br>\n");
      out.write("		<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;13:00 - 17:00</span><br>\n");
      out.write("		<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sat.sun.holiday off</span><br>\n");
      out.write("    </li>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  \n");
      out.write("\n");
      out.write("</aside>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/3624917c4f.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style1.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"./js/main.js\" defer></script>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("html,\n");
      out.write("body {\n");
      out.write("    height: 150%;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("     z-index: 2; \n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".frame-container iframe {\n");
      out.write("    width: 45%;\n");
      out.write("    height: auto;\n");
      out.write("    border: none;\n");
      out.write("    z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".frame-container iframe:nth-child(2) {\n");
      out.write("    margin-left: 5%; /* Gender.jsp와의 간격 조절 */\n");
      out.write("    z-index: 2; /* z-index 적용 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".spacing {\n");
      out.write("    height: 10px;\n");
      out.write("    z-index: 2; /* z-index 적용 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    background: linear-gradient(180deg, rgba(228, 220, 207, 1) 0%, rgba(245, 240, 187, 1) 38%, rgba(125, 157, 156, 1) 100%);\n");
      out.write("    height: calc(100% + 100px); /* header 높이 고려하여 계산 */\n");
      out.write("    z-index: 2; /* z-index 적용 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".frame-container {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    width: 80%;\n");
      out.write("    height: 100%;\n");
      out.write("    z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".check {\n");
      out.write("    margin-top: -50%; /* 버튼을 위로 이동 */\n");
      out.write("    margin-left: 10%;\n");
      out.write("    width: 20%;\n");
      out.write("    justify-content: space-around;\n");
      out.write("    z-index: 2; /* z-index 적용 */\n");
      out.write("}\n");
      out.write("        .manager-iframe {\n");
      out.write("            position: absolute;\n");
      out.write("            left: calc(70% - 70px);\n");
      out.write("            width: calc(20% - 30px);\n");
      out.write("            height: calc(50% + 300px);\n");
      out.write("            margin-top: 90px;\n");
      out.write("            z-index: 2; /* 낮은 z-index 값으로 설정하여 뒤쪽에 배치 */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"navbar__logo\">\n");
      out.write("            \n");
      out.write("            <a href=\"manager.do\">\n");
      out.write("    <img src=\"./images/CompanyLogo.png\" alt=\"로고\" style=\"width: 82.2px; margin-top:45.2px; margin-left: 38.5px;\">\n");
      out.write("</a>\n");
      out.write("        </div>\n");
      out.write("                <ul class=\"navbar__menu\">\n");
      out.write("            <li><a href=\"manager.do\">회원관리</a></li>\n");
      out.write("            <li><a href=\"productmanager.do\">상품관리</a></li>\n");
      out.write("            <li><a href=\"totalmanager.do\">매출</a></li>\n");
      out.write("            <li><a href=\"#\">게시판관리</a></li>\n");
      out.write("            <li><a href=\"logout.do\">로그아웃</a></li>\n");
      out.write("            \n");
      out.write("        </ul>\n");
      out.write("        <ul class=\"navbar__links\">\n");
      out.write("            <li><a href=\"https://www.youtube.com/channel/UCNzODSZC2sraPyh4lDMQhpQ?view_as=subscriber\"><i class=\"fab fa-youtube\"></i></a></li>\n");
      out.write("            <li><a href=\"https://www.instagram.com/faderoom_official/\"><i class=\"fab fa-instagram\"></i></a></li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <a href=\"#\" class=\"navbar__toggleBtn\"><i class=\"fas fa-bars\"></i></a>\n");
      out.write("    </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"content\">\n");
      out.write("\n");
      out.write("    <div class=\"frame-container\" >\n");
      out.write("        <iframe src=\"./admin/Manager.jsp\" frameborder=\"0\" style=\"width: 60%; margin-top: 50px;z-index: 3;\"></iframe>\n");
      out.write("        <iframe src=\"./admin/Gender.jsp\" frameborder=\"0\" style=\"position: absolute; left: calc(70% - 70px); width: calc(20% - 30px); height: calc(50% + 300px); margin-top: 90px;\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    <iframe src=\"./UserTable.jsp\" frameborder=\"0\" style=\"position: absolute; width: 80%; height: 45%; margin: 10px auto; align-items: center; z-index: 999\"></iframe>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/js/queryTable.js\"></script>\n");
      out.write("<script>\n");
      out.write("    // 창 크기가 변경될 때 iframe의 크기를 다시 계산하여 조절하는 함수\n");
      out.write("    function resizeIframes() {\n");
      out.write("        const frameContainers = document.querySelectorAll('.frame-container');\n");
      out.write("        frameContainers.forEach(container => {\n");
      out.write("            const iframes = container.querySelectorAll('iframe');\n");
      out.write("            iframes.forEach(iframe => {\n");
      out.write("                iframe.style.height = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${container.offsetHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px`;\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 문서가 완전히 로드된 후에 실행되는 함수\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        // 창 크기가 변경될 때 iframe의 크기를 다시 계산하여 조절\n");
      out.write("        $(window).resize(resizeIframes);\n");
      out.write("        resizeIframes(); // 초기 로드 시 iframe 크기 조절\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<!-- ============================== [[ Header  section]] ==============================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("\n");
      out.write("	\n");
      out.write("<!-- ============================== [[ Sidebar  section]] ==============================-->\n");
      out.write("<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("<!-- ============================== [[ Body  section]] ==============================-->\n");
      out.write("\n");
      out.write("<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("\n");
      out.write("<!-- =============================  [[ Footer section ]]  ============================= -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
